// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRDIJ_AL2D6uxvxBO8j0mt-7da0UEyCI',
    appId: '1:1084136492076:web:d1b5549c51e6835a4b5589',
    messagingSenderId: '1084136492076',
    projectId: 'giziku-database',
    authDomain: 'giziku-database.firebaseapp.com',
    storageBucket: 'giziku-database.firebasestorage.app',
    measurementId: 'G-8YE5XMQKE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfASD1J7Hc84cF19hxruVF5bQ6WL8SIqs',
    appId: '1:1084136492076:android:489abc8ab96a39924b5589',
    messagingSenderId: '1084136492076',
    projectId: 'giziku-database',
    storageBucket: 'giziku-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE07-Lx6LakLDmOHw_Lyz2ajljEI9sJtk',
    appId: '1:1084136492076:ios:5f8a76562751233f4b5589',
    messagingSenderId: '1084136492076',
    projectId: 'giziku-database',
    storageBucket: 'giziku-database.firebasestorage.app',
    iosBundleId: 'com.example.gizikuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE07-Lx6LakLDmOHw_Lyz2ajljEI9sJtk',
    appId: '1:1084136492076:ios:5f8a76562751233f4b5589',
    messagingSenderId: '1084136492076',
    projectId: 'giziku-database',
    storageBucket: 'giziku-database.firebasestorage.app',
    iosBundleId: 'com.example.gizikuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlRDIJ_AL2D6uxvxBO8j0mt-7da0UEyCI',
    appId: '1:1084136492076:web:c4e4cbe0b8f932fa4b5589',
    messagingSenderId: '1084136492076',
    projectId: 'giziku-database',
    authDomain: 'giziku-database.firebaseapp.com',
    storageBucket: 'giziku-database.firebasestorage.app',
    measurementId: 'G-023Q8NZJPP',
  );

}