name: giziku_app
description: "A new Flutter project."
# Mencegah publikasi tidak sengaja ke pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Menggunakan rentang SDK yang lebih fleksibel

dependencies:
  flutter:
    sdk: flutter

  # --- PAKET YANG DIGUNAKAN DALAM APLIKASI ---
  # Ikon dasar untuk aplikasi Flutter.
  cupertino_icons: ^1.0.8
  
  # Diperlukan untuk format tanggal (misalnya di halaman statistik).
  intl: ^0.19.0 
  
  # Untuk membuat grafik statistik yang interaktif.
  fl_chart: ^0.68.0 
  
  # Diperlukan untuk memilih gambar dari galeri (untuk foto profil).
  image_picker: ^1.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Paket untuk membantu menemukan dan memperbaiki error gaya kode.
  flutter_lints: ^4.0.0


# Konfigurasi spesifik untuk Flutter.
flutter:
  uses-material-design: true

  # --- ASET/GAMBAR YANG DIGUNAKAN ---
  # Pastikan Anda memiliki folder 'assets' di root proyek Anda.
  assets:
    - assets/logo.png
    - assets/makanan1.png # Disesuaikan menjadi .jpg seperti pada HomeScreen